datasource.host=${MYSQL_HOST:localhost}
datasource.port=${MYSQL_PORT:3306}
datasource.name=${MYSQL_DB}
datasource.username=${MYSQL_USER}
datasource.password=${MYSQL_PASSWORD}
datasource.url=jdbc:mysql://${datasource.host}:${datasource.port}/${datasource.name}
datasource.driver-class-name=com.mysql.cj.jdbc.Driver