datasource.host=${POSTGRES_HOST:localhost}
datasource.port=${POSTGRES_PORT:5432}
datasource.name=${POSTGRES_DB:kbinvestory}
datasource.username=${POSTGRES_USER:postgres}
datasource.password=${POSTGRES_PASSWORD:postgres}
datasource.url=jdbc:postgresql://${datasource.host}:${datasource.port}/${datasource.name}
datasource.driver-class-name=org.postgresql.Driver